package constants

import "time"

// Session constants
const (
	// SessionMaxAge is the maximum age of a session in seconds (7 days)
	SessionMaxAge = 7 * 24 * 60 * 60

	// SessionCookieName is the name of the session cookie
	SessionCookieName = "session"
)

// Pagination constants
const (
	// DefaultPageSize is the default number of items per page
	DefaultPageSize = 20

	// MaxPageSize is the maximum number of items per page
	MaxPageSize = 100

	// MinPageSize is the minimum number of items per page
	MinPageSize = 1
)

// Validation constants
const (
	// MinPasswordLength is the minimum password length
	MinPasswordLength = 8

	// MaxPasswordLength is the maximum password length
	MaxPasswordLength = 128

	// MinNameLength is the minimum name length
	MinNameLength = 1

	// MaxNameLength is the maximum name length
	MaxNameLength = 100

	// MaxDescriptionLength is the maximum description length
	MaxDescriptionLength = 5000
)

// AI Service constants
const (
	// MaxAIGeneratedTasks is the maximum number of tasks that can be generated by AI
	MaxAIGeneratedTasks = 50

	// AIRequestTimeout is the timeout for AI service requests
	AIRequestTimeout = 30 * time.Second
)

// Cache constants
const (
	// DefaultCacheTTL is the default cache time-to-live
	DefaultCacheTTL = 5 * time.Minute

	// OrganizationMembershipCacheTTL is the cache TTL for organization memberships
	OrganizationMembershipCacheTTL = 10 * time.Minute
)

// Context keys (used for storing values in gin.Context)
const (
	// ContextKeyUserID is the key for user ID in context
	ContextKeyUserID = "user_id"

	// ContextKeyTask is the key for task in context
	ContextKeyTask = "task"

	// ContextKeyOrganization is the key for organization in context
	ContextKeyOrganization = "organization"

	// ContextKeyOrganizationMember is the key for organization member in context
	ContextKeyOrganizationMember = "organization_member"
)
